{
  "hash": "2ee2f3ee940d0840c63f4ff2fa3ff1bb",
  "result": {
    "markdown": "---\ntitle: \"Heron Package\"\ndescription: \"Le package heron permet de claculer l'aire d'un triangle en prenant comme argument ses 3 longueurs.\"\nauthor: \"LE ROUX Noa\"\ndate: \"2023-20-02\"\nimage: \"heron.png\"\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(quarto)\nlibrary(targets)\n```\n:::\n\n\n[Comment installer le package via \"*remotes*\" ?]{.underline}\n\nInstaller le package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(remotes)\ninstall_github(\"NoaLRX/heron\")\nlibrary(heron)\n```\n:::\n\n\n## Package heron\n\nLe package heron comprend la fonction heron ainsi que la fonction demi-perimetre avec :\n\n-   [**heron**]{.underline}: permet de calculer *(via la formule de heron)* l'aire d'un triangle à partir de la longueur de ses 3 côtés *(a,b,c)*\n\n-   [**demi-perimetre:**]{.underline} permet de calculer le demi-perimetre du triangle à partir de la longueur de ses 3 côtés *(a,b,c)*\n\nLa formule d'heron est la suivante:\n\n$Aire = \\sqrt{p\\times(p-a)(p-b)(p-c)}$\n\navec:\n\n-   $a,b,c$ les côtés du triangle\n\n-   $p$ le demi-périmètre tel que $p\\ = \\frac{a+b+c}{2}$\n\n## Triangle de Serpiński\n\nLe Triangle de Sierpinski est une forme géométrique qui peut être créée en divisant un triangle en plusieurs petits triangles plus petits. Ensuite, on répète ce processus pour chaque petit triangle créé, encore et encore. Cela crée une sorte de \"puzzle\" de triangles imbriqués les uns dans les autres. Cette forme peut être utile pour étudier des idées mathématiques et pour créer des images intéressantes. On peut également l'utiliser pour étudier des choses dans la nature comme la croissance des cristaux ou des plantes.\n\n### Exemple\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntriangles = matrix(c(0, 0, 1, 0, 0.5, sqrt(3)/2), nrow = 3, ncol = 2)\n```\n:::\n\n\n### Itération 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"plot1\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"aire1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.25\n```\n:::\n:::\n\n\nLa somme des aires est de 0.25\n\n### Itération 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"plot2\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"aire2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1875\n```\n:::\n:::\n\n\nLa somme des aires est de 0.1875\n\n### Itération 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"plot3\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntar_read(\"aire3\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.140625\n```\n:::\n:::\n\n\nLa somme des aires est de 0.140625\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}